# Generated by Django 5.2.9 on 2025-12-03 16:36

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Article Index",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        default="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
                        help_text="Robots meta tag value",
                        max_length=100,
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True,
                        help_text="Brief introduction shown in article listings",
                        max_length=500,
                    ),
                ),
                ("body", wagtail.fields.RichTextField()),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media sharing (recommended: 1200x630px)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
