# Generated by Django 5.2.9 on 2025-12-03 16:52

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
