# Generated by Django 5.2.9 on 2025-12-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_articlepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="embedding_visualization",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="Pre-computed 2D coordinates for embedding visualization",
                null=True,
            ),
        ),
    ]
