# Generated by Django 5.2.9 on 2025-12-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_add_embedding_visualization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="embedding_visualization",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="Pre-computed coordinates for embedding visualization",
                null=True,
            ),
        ),
    ]
