# Generated by Django 5.2.9 on 2025-12-03 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_phone_user_profile_image_workexperience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
    ]
