# Generated by Django 5.2.9 on 2025-12-03 16:07

import resolve.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_convert_workexperience_to_orderable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=resolve.fields.PhoneField(),
        ),
    ]
