# Generated by Django 5.2.7 on 2025-12-03 11:24

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Resolve", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("telephone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "address_country",
                    models.CharField(blank=True, default="Netherlands", max_length=100),
                ),
                (
                    "price_range",
                    models.CharField(blank=True, default="€€€", max_length=10),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True, default="Mo-Fr 09:00-18:00", max_length=100
                    ),
                ),
                (
                    "founder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Information",
            },
        ),
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Resolve", help_text="Footer heading", max_length=100
                    ),
                ),
                (
                    "column_1",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("definition_list", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Definition term (dt)",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Definition description (dd)",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("term", 1), ("definition", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                            5: ("wagtail.blocks.StructBlock", [[("items", 4)]], {}),
                        },
                        help_text="First footer column content",
                    ),
                ),
                (
                    "column_2",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("definition_list", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Definition term (dt)",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Definition description (dd)",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("term", 1), ("definition", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                            5: ("wagtail.blocks.StructBlock", [[("items", 4)]], {}),
                        },
                        help_text="Second footer column content",
                    ),
                ),
                (
                    "column_3",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("definition_list", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Definition term (dt)",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Definition description (dd)",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("term", 1), ("definition", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                            5: ("wagtail.blocks.StructBlock", [[("items", 4)]], {}),
                        },
                        help_text="Third footer column content",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        default="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
                        help_text="Robots meta tag value",
                        max_length=100,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("hero", 4), ("section", 35)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Main heading text",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Body text for the hero section",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {
                                    "help_text": "Email address for contact",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Phone number for contact",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 0),
                                        ("body_text", 1),
                                        ("cta_email", 2),
                                        ("cta_phone", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Section title (h2)",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("light", "Light"), ("dark", "Dark")],
                                    "help_text": "Section background color",
                                },
                            ),
                            7: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["h3"], "help_text": "Heading (h3)"},
                            ),
                            8: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Paragraph of text",
                                },
                            ),
                            9: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("3", "3 columns"), ("4", "4 columns")],
                                    "help_text": "Number of columns in grid layout",
                                },
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 100, "required": True},
                            ),
                            11: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 10), ("description", 11)]],
                                {},
                            ),
                            13: ("wagtail.blocks.ListBlock", (12,), {}),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("columns", 9), ("features", 13)]],
                                {},
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Definition term (dt)",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            16: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Definition description (dd)",
                                    "required": True,
                                },
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("term", 15), ("definition", 16)]],
                                {},
                            ),
                            18: ("wagtail.blocks.ListBlock", (17,), {}),
                            19: ("wagtail.blocks.StructBlock", [[("items", 18)]], {}),
                            20: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Image on left"),
                                        ("right", "Image on right"),
                                    ],
                                    "help_text": "Which side to place the image",
                                },
                            ),
                            21: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Image for the column", "required": True},
                            ),
                            22: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 7),
                                        ("paragraph", 8),
                                        ("definition_list", 19),
                                    ]
                                ],
                                {
                                    "help_text": "Content for the text column",
                                    "required": True,
                                },
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image_position", 20),
                                        ("image", 21),
                                        ("content", 22),
                                    ]
                                ],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The question",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            25: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "The answer",
                                    "required": True,
                                },
                            ),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 24), ("answer", 25)]],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.ListBlock",
                                (26,),
                                {"help_text": "FAQ items"},
                            ),
                            28: ("wagtail.blocks.StructBlock", [[("items", 27)]], {}),
                            29: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Step title (e.g., 'Diagnose', 'Prototype')",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            30: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Brief description of this step",
                                    "required": True,
                                },
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 29), ("description", 30)]],
                                {},
                            ),
                            32: (
                                "wagtail.blocks.ListBlock",
                                (31,),
                                {
                                    "help_text": "Exactly 4 process steps (arrows connect first 3)",
                                    "max_num": 4,
                                    "min_num": 4,
                                },
                            ),
                            33: ("wagtail.blocks.StructBlock", [[("steps", 32)]], {}),
                            34: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 7),
                                        ("paragraph", 8),
                                        ("features", 14),
                                        ("definition_list", 19),
                                        ("two_column", 23),
                                        ("faq", 28),
                                        ("process_roadmap", 33),
                                    ]
                                ],
                                {"required": False},
                            ),
                            35: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 5), ("background", 6), ("content", 34)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media sharing (recommended: 1200x630px)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
