# Generated by Django 5.2.9 on 2025-12-03 14:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 4), ("section", 37)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading text",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Body text for the hero section",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Email address for contact", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Phone number for contact",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("body_text", 1),
                                ("cta_email", 2),
                                ("cta_phone", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Section title (h2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("light", "Light"), ("dark", "Dark")],
                            "help_text": "Section background color",
                        },
                    ),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["h3"], "help_text": "Heading (h3)"},
                    ),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Paragraph of text",
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("3", "3 columns"), ("4", "4 columns")],
                            "help_text": "Number of columns in grid layout",
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 10), ("description", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("columns", 9), ("features", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Definition term (dt)",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Definition description (dd)",
                            "required": True,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 15), ("definition", 16)]],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {}),
                    19: ("wagtail.blocks.StructBlock", [[("items", 18)]], {}),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Image on left"),
                                ("right", "Image on right"),
                            ],
                            "help_text": "Which side to place the image",
                        },
                    ),
                    21: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image for the column", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 7), ("paragraph", 8), ("definition_list", 19)]],
                        {"help_text": "Content for the text column", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("image_position", 20), ("image", 21), ("content", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The question",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "The answer",
                            "required": True,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 24), ("answer", 25)]],
                        {},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {"help_text": "FAQ items"}),
                    28: ("wagtail.blocks.StructBlock", [[("items", 27)]], {}),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Step title (e.g., 'Diagnose', 'Prototype')",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Brief description of this step",
                            "required": True,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 29), ("description", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.ListBlock",
                        (31,),
                        {
                            "help_text": "Exactly 4 process steps (arrows connect first 3)",
                            "max_num": 4,
                            "min_num": 4,
                        },
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("steps", 32)]], {}),
                    34: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("accounts.User",),
                        {},
                    ),
                    35: ("wagtail.blocks.StructBlock", [[("user", 34)]], {}),
                    36: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 7),
                                ("paragraph", 8),
                                ("features", 14),
                                ("definition_list", 19),
                                ("two_column", 23),
                                ("faq", 28),
                                ("process_roadmap", 33),
                                ("about_user", 35),
                            ]
                        ],
                        {"required": False},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("background", 6), ("content", 36)]],
                        {},
                    ),
                },
            ),
        ),
    ]
