# Generated by Django 5.2.9 on 2025-12-03 15:45

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_homepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footersettings",
            name="column_1",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="column_2",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="column_3",
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="address",
            field=models.TextField(blank=True, help_text="Full business address"),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="github_url",
            field=models.URLField(blank=True, help_text="GitHub profile URL"),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="linkedin_url",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL"),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="register_url",
            field=models.URLField(blank=True, help_text="Business register URL"),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="vat_number",
            field=models.CharField(
                blank=True, help_text="VAT registration number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="tagline",
            field=wagtail.fields.StreamField(
                [("paragraph", 0)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    )
                },
                help_text="Footer tagline content",
            ),
        ),
    ]
