# Generated by Django 5.2.9 on 2025-12-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_move_footer_to_business_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="registration_note",
            field=models.CharField(
                blank=True,
                help_text="Note displayed below business registration info (e.g. 'Estonian e-residency program')",
                max_length=200,
            ),
        ),
    ]
