# Generated by Django 5.2.9 on 2025-12-03 16:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_add_registration_note"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesssettings",
            options={"verbose_name": "Business"},
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 2), ("section", 35)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading text",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Body text for the hero section",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("body_text", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Section title (h2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("light", "Light"), ("dark", "Dark")],
                            "help_text": "Section background color",
                        },
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["h3"], "help_text": "Heading (h3)"},
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Paragraph of text",
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("3", "3 columns"), ("4", "4 columns")],
                            "help_text": "Number of columns in grid layout",
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 8), ("description", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns", 7), ("features", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Definition term (dt)",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Definition description (dd)",
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 13), ("definition", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: ("wagtail.blocks.StructBlock", [[("items", 16)]], {}),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Image on left"),
                                ("right", "Image on right"),
                            ],
                            "help_text": "Which side to place the image",
                        },
                    ),
                    19: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image for the column", "required": True},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 5), ("paragraph", 6), ("definition_list", 17)]],
                        {"help_text": "Content for the text column", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("image_position", 18), ("image", 19), ("content", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The question",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    23: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "The answer",
                            "required": True,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 22), ("answer", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.ListBlock", (24,), {"help_text": "FAQ items"}),
                    26: ("wagtail.blocks.StructBlock", [[("items", 25)]], {}),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Step title (e.g., 'Diagnose', 'Prototype')",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    28: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Brief description of this step",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 27), ("description", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.ListBlock",
                        (29,),
                        {
                            "help_text": "Exactly 4 process steps (arrows connect first 3)",
                            "max_num": 4,
                            "min_num": 4,
                        },
                    ),
                    31: ("wagtail.blocks.StructBlock", [[("steps", 30)]], {}),
                    32: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("accounts.User",),
                        {},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("user", 32)]], {}),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 5),
                                ("paragraph", 6),
                                ("features", 12),
                                ("definition_list", 17),
                                ("two_column", 21),
                                ("faq", 26),
                                ("process_roadmap", 31),
                                ("about_user", 33),
                            ]
                        ],
                        {"required": False},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("background", 4), ("content", 34)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.CreateModel(
            name="ContactSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        default="Free consultation request",
                        help_text="Subject line for contact emails",
                        max_length=200,
                    ),
                ),
                (
                    "email_body",
                    models.TextField(
                        default="Hi,\n\nWe're curious about how you could help us with our current challenge.\n\n...\n\nBest regards,\n...",
                        help_text="Default email body template",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
            },
        ),
    ]
