# Generated by Django 5.2.9 on 2025-12-03 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_add_contact_settings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businesssettings",
            old_name="telephone",
            new_name="phone",
        ),
    ]
