# Generated by Django 5.2.9 on 2025-12-03 16:07

import resolve.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_rename_telephone_to_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssettings",
            name="phone",
            field=resolve.fields.PhoneField(),
        ),
    ]
