# Generated by Django 5.2.9 on 2025-12-03 16:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_businesssettings_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footersettings",
            name="tagline",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Footer tagline content"
            ),
        ),
    ]
