# Generated by Django 5.2.9 on 2025-12-04 14:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_convert_tagline_to_richtextfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 2), ("section", 34)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading text",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Body text for the hero section",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("body_text", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Section title (h2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("light", "Light"), ("dark", "Dark")],
                            "help_text": "Section background color",
                        },
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["h3"], "help_text": "Heading (h3)"},
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Paragraph of text",
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("3", "3 columns"), ("4", "4 columns")],
                            "help_text": "Number of columns in grid layout",
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 8), ("description", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns", 7), ("features", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Definition term (dt)",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Definition description (dd)",
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 13), ("definition", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: ("wagtail.blocks.StructBlock", [[("items", 16)]], {}),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Image on left"),
                                ("right", "Image on right"),
                            ],
                            "help_text": "Which side to place the image",
                        },
                    ),
                    19: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image for the column", "required": True},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 5), ("paragraph", 6), ("definition_list", 17)]],
                        {"help_text": "Content for the text column", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("image_position", 18), ("image", 19), ("content", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The question",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    23: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "The answer",
                            "required": True,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 22), ("answer", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.ListBlock", (24,), {"help_text": "FAQ items"}),
                    26: ("wagtail.blocks.StructBlock", [[("items", 25)]], {}),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Step title (e.g., 'Diagnose', 'Prototype')",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    28: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Brief description of this step",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 27), ("description", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.ListBlock",
                        (29,),
                        {
                            "help_text": "Exactly 4 process steps (arrows connect first 3)",
                            "max_num": 4,
                            "min_num": 4,
                        },
                    ),
                    31: ("wagtail.blocks.StructBlock", [[("steps", 30)]], {}),
                    32: ("wagtail.blocks.StructBlock", [[]], {}),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 5),
                                ("paragraph", 6),
                                ("features", 12),
                                ("definition_list", 17),
                                ("two_column", 21),
                                ("faq", 26),
                                ("process_roadmap", 31),
                                ("about_founder", 32),
                            ]
                        ],
                        {"required": False},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("background", 4), ("content", 33)]],
                        {},
                    ),
                },
            ),
        ),
    ]
