# Generated by Django 5.2.9 on 2025-12-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="embedding_visualization",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="Pre-computed coordinates for embedding visualization",
                null=True,
            ),
        ),
    ]
