# Generated by Django 5.2.9 on 2025-12-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_homepage_embedding_visualization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footersettings",
            name="heading",
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="name",
            field=models.CharField(default="Resolve.", max_length=100),
        ),
    ]
